server:
  port: 8080


spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
