server:
  port: 80


spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
#      ddl-auto: create
    open-in-view: false
  queries:
    users-query: select username, password, active from user where username = ?
    roles-query: select u.username, ur.name from user u right join role ur on (u.role_id = ur.id) where u.username = ?


contextio:
  key: b3owis1w
  client-secret: kQu4fxlTYzQ5PjJU
